# Site settings
title: "YuSa64"
email: rtgh64@gmail.com
url: https://github.com/YuSa64
description: "유사의 VRC포트폴리오"
keywords: "VRChat, VR챗"
skills: "VRC Avatar - Blender - Substance 3D Painter"
meta_author: YuSa64

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: bab0ff
  primary-rgb: "186,176,255"
  secondary: 010101
  secondary-dark: FF9999

# Footer settings
footer:
  copyright: "YuSa64"
  location: "서식지"
  social:
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/yusa64_vr
  - title: instagram
    url: https://t.co/RT4xaIdXf2
  - title: github
    url: https://github.com/YuSa64

# Postal address (add as many lines as necessary)
address:
  - line: "루석바"
  - line: 

# Credits content
credits: 'YuSa64'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
